# version: 2
# updates:
#   - package-ecosystem: 'github-actions'
#     directory: '/'
#     schedule:
#       interval: 'daily'

#   - package-ecosystem: "npm"
#     directory: "/frontend/"
#     schedule:
#       interval: "daily"

#   - package-ecosystem: "docker"
#     directory: "/frontend/"
#     schedule:
#       interval: "daily"

#   - package-ecosystem: 'docker'
#     directory: '/backend/'
#     schedule:
#       interval: 'weekly'
#     ignore:
#       - dependency-name: 'python'

#   - package-ecosystem: 'pip'
#     directory: '/backend/'
#     schedule:
#       interval: 'daily'
